{ config
, pkgs
, ...
}:
# Self-hosted World Monitor (https://github.com/koala73/worldmonitor) via upstream
# docker compose. Dashboard on 127.0.0.1:3000; Tailscale Serve HTTPS on :3000.
# Required secrets (agenix → repo .env): RELAY_SHARED_SECRET, REDIS_PASSWORD, REDIS_TOKEN.
let
  stateDir = "/var/lib/worldmonitor";
  repoDir = "${stateDir}/repo";
  # Pin for reproducible checkouts; bump intentionally when upgrading.
  repoUrl = "https://github.com/koala73/worldmonitor.git";
  repoRev = "9ec82ebda56ddb0e8ba3552651aca6b26bb8347c";

  composeOverride = pkgs.writeText "worldmonitor-compose.override.yml" ''
    # Generated by modules/services/worldmonitor.nix — localhost bind + relay auth.
    services:
      worldmonitor:
        ports: !override
          - "127.0.0.1:3000:8080"
        environment:
          RELAY_SHARED_SECRET: "''${RELAY_SHARED_SECRET:?RELAY_SHARED_SECRET required}"
      ais-relay:
        environment:
          RELAY_SHARED_SECRET: "''${RELAY_SHARED_SECRET:?RELAY_SHARED_SECRET required}"
  '';
in
{
  age.secrets.worldmonitor-env = {
    file = ../../secrets/worldmonitor-env.age;
    mode = "0400";
  };

  systemd.tmpfiles.rules = [
    "d ${stateDir} 0750 root root -"
  ];

  # Shallow-fetch pinned commit, install compose override, scripts npm deps for seeders.
  systemd.services.worldmonitor-repo = {
    description = "Fetch World Monitor repo at pinned revision";
    wantedBy = [ "multi-user.target" ];
    before = [ "worldmonitor.service" ];
    after = [ "network-online.target" ];
    wants = [ "network-online.target" ];
    path = [
      pkgs.git
      pkgs.nodejs_22
      pkgs.coreutils
      pkgs.gnugrep
    ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      TimeoutStartSec = "30min";
    };
    script = ''
      set -euo pipefail
      if [ ! -d ${repoDir}/.git ]; then
        rm -rf ${repoDir}
        mkdir -p ${repoDir}
        git -C ${repoDir} init
        git -C ${repoDir} remote add origin ${repoUrl}
      fi
      git -C ${repoDir} fetch --depth 1 origin ${repoRev}
      git -C ${repoDir} checkout --force FETCH_HEAD
      install -m 0644 ${composeOverride} ${repoDir}/docker-compose.override.yml
      # Seeders run on the host against redis-rest; only scripts/ deps are required.
      npm ci --prefix ${repoDir}/scripts --omit=dev --omit=optional --ignore-scripts
    '';
  };

  systemd.services.worldmonitor = {
    description = "World Monitor docker compose stack";
    wantedBy = [ "multi-user.target" ];
    after = [
      "network-online.target"
      "docker.service"
      "worldmonitor-repo.service"
    ];
    requires = [
      "docker.service"
      "worldmonitor-repo.service"
    ];
    wants = [ "network-online.target" ];
    path = [
      pkgs.docker
      pkgs.docker-compose
      pkgs.coreutils
    ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      WorkingDirectory = repoDir;
      TimeoutStartSec = "2h";
      TimeoutStopSec = "5min";
      ExecStop = "${pkgs.docker-compose}/bin/docker-compose --project-directory ${repoDir} down";
    };
    script = ''
      set -euo pipefail
      install -m 0400 ${config.age.secrets.worldmonitor-env.path} ${repoDir}/.env
      ${pkgs.docker-compose}/bin/docker-compose up -d --build --remove-orphans
    '';
  };

  # Upstream seeders fill Redis; public feeds work without API keys.
  systemd.services.worldmonitor-seeders = {
    description = "World Monitor Redis seeders";
    after = [ "worldmonitor.service" ];
    requires = [ "worldmonitor.service" ];
    path = [
      pkgs.nodejs_22
      pkgs.coreutils
      pkgs.gnugrep
      pkgs.gnused
      pkgs.bash
    ];
    serviceConfig = {
      Type = "oneshot";
      WorkingDirectory = repoDir;
      TimeoutStartSec = "2h";
    };
    script = ''
      set -euo pipefail
      install -m 0400 ${config.age.secrets.worldmonitor-env.path} ${repoDir}/.env
      ${pkgs.bash}/bin/bash ${repoDir}/scripts/run-seeders.sh
    '';
  };

  systemd.timers.worldmonitor-seeders = {
    description = "Re-seed World Monitor Redis every 30 minutes";
    wantedBy = [ "timers.target" ];
    timerConfig = {
      OnBootSec = "3min";
      OnUnitActiveSec = "30min";
      Persistent = true;
      RandomizedDelaySec = "2min";
      Unit = "worldmonitor-seeders.service";
    };
  };
}
